application: lollysite
version: v0-02-00
runtime: python
api_version: 1
default_expiration: '1d'

handlers:
- url: /admin/remote
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /admin/.*
  script: admin.py
  login: admin

- url: /_ah/queue/.*
  script: queue.py
  login: admin

- upload: theme/[^/]+/static/.*      # all the files to upload
  url: /static/([^/]+)/(.*)          # the paths this handler will serve
  static_files: theme/\1/static/\2   # where the files actually live (on the server)

- url: /test/.*
  script: test.py
  login: admin

- url: /node/.*
  script: node.py

- url: /.*
  script: lollysite.py

skip_files:
- ^(.*/)?app\.yaml$
- ^(.*/)?app\.yml$
- ^(.*/)?index\.yaml$
- ^(.*/)?index\.yml$
- ^(.*/)?.*\.log$
- ^(.*/)?.*\.dat$
- ^(.*/)?.*\.py[co]$           # compiled Python
- ^(.*/)?.*/RCS/.*             # any RCS files
- ^(.*/)?\..*                  # dotfiles
- ^(.*/)?#.*#                  # emacs autosave
- ^(.*/)?.*~$                  # backup files
- ^issues/.*                   # cil issues
- ^store/.*                    # local datastore
- ^logs/.*                     # downloaded logs
- ^google_appengine/.*         # the SDK
- ^Makefile
- ^README
- ^LICENSE
